### ISSUE TITLE
WIP, Simulation etc. not found in module

### ISSUE THREAD

**Issue by olantwin** [DUNE/dune-plot-style#15]
Edit: Seems like a packaging issue, investigating...

~~We should at least provide empty placeholders for these methods, so that the examples run.~~

~~- [ ] `Simulation`~~
~~- [ ] `SimulationSide`~~
~~- [ ] `CornerLabel`~~
~~- [ ] `WIP`~~

~~CC @andrewmogan @admlw~~

~~The examples themselves look good :)~~

**Comment by andrewmogan** [comment]
Has this been resolved yet?

**Comment by olantwin** [comment]
I actually managed to get this again today, but don't understand why. When properly installed, this doesn't happen. I think until we find a way to reproduce this, we can probably close it.
